### ISSUE TITLE
Temporarily-broken record invariants

### ISSUE THREAD

**Issue by utting** [Whiley/Whiley2Boogie#113] opened 2021-04-29 06:23 UTC
There seems to be a problem with the current Boogie code generated when multiple fields of a record are updated in a single assignment statement, and the record has an invariant that is maintained by the multiple assignment, but would be broken by individual assignments.

For example, the attached program gives a Boogie error 'type invariant may not be satisfied' on the p.a+1 expression on line 10.

This is because the generated Boogie does the record update one field at a time, but checks the record invariant after *every* update, instead of just at the end of all the updates.

[MultiAssign.whiley.txt](https://github.com/Whiley/Whiley2Boogie/files/6396640/MultiAssign.whiley.txt)

More generally, this can also be a problem at the Whiley level. 
For example the following code (from https://github.com/uqcyber/VeriSmart/blob/main/casino/src/casino.whiley)::
  function addToPot(Casino casino, uint256 value) -> (Casino out)
  requires byOperator(casino)
  requires costs(casino, value)
  requires value > 0
  requires value <= casino.operator.balance
  requires casino.address.balance + value < MAX256
  ensures out.pot == casino.pot + value:
    (casino.address, casino.msg.sender) = payable(casino.address, casino.msg)
    casino.pot = casino.pot + value
    return casino

fails to verify (when the Casino type includes the valid invariant) because the Casino invariant is temporarily broken inbetween the two assignments (until the casino.pot value is also updated).  It would be nice to have some way of only checking the type invariants after all the assignments, rather than at every step.

**Comment by DavePearce** [comment] 2021-05-04 00:36
Hey Mark,

Yeah, I think i'm aware of this.  It looks like a duplicate of this issue:

https://github.com/Whiley/Whiley2Boogie/issues/99

At some point, I will most definitely fix this.  Right now, probably not a priority until I get more progress on the paper!!

**Comment by DavePearce** [comment] 2021-05-13 07:43
Fixed now

**Closed by DavePearce** 2021-05-13 07:43 UTC
